#!/bin/bash

COMMON_FLAGS="-D'BUILD_KEY=f0b9c4c170d1037daa8a9669cbae91b4' \
			  -D'RELEASE_NAME=4.5.3' \
			  -DCLOUD_BUILD \
			  -DUSE_DSHOT \
			  -DUSE_LED_STRIP \
			  -DUSE_PINIO \
			  -DUSE_SERIALRX -DUSE_SERIALRX_GHST \
			  -DUSE_TELEMETRY -DUSE_TELEMETRY_GHST \
			  -DUSE_OSD -DUSE_OSD_SD -DUSE_VTX"
CUSTOM_FLAGS="-DUSE_MSP_MOTOR_OVERRIDE"

make FOXEERH743 EXTRA_FLAGS="$COMMON_FLAGS $CUSTOM_FLAGS"