#!/bin/bash

COMMON_FLAGS="-D'BUILD_KEY=37bb7b7b0d429089df1b4ac065109366' \
			  -D'RELEASE_NAME=4.5.3' \
			  -DCLOUD_BUILD \
			  -DUSE_DSHOT \
			  -DUSE_LED_STRIP \
			  -DUSE_PINIO \
			  -DUSE_SERIALRX -DUSE_SERIALRX_GHST \
			  -DUSE_TELEMETRY -DUSE_TELEMETRY_GHST \
			  -DUSE_OSD -DUSE_OSD_SD -DUSE_VTX"
CUSTOM_FLAGS=""

make FOXEERH743 EXTRA_FLAGS="$COMMON_FLAGS $CUSTOM_FLAGS"